### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by pvnr0082t** [i-break-codes/logerr#21]
Hi @i-break-codes ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we're going to host this library.
The git auto-updater in cdnjs relies on **[git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)** so that it can recognize the correct version and automatically update the repo. 
Could you please add git tags for the repo? Thank you.

https://github.com/cdnjs/cdnjs/issues/9364

**Comment by i-break-codes** [comment]
Done, thanks a lot :) https://github.com/i-break-codes/logerr/releases/tag/1.2.0

Let me know if something else needs to be done.

**Comment by pvnr0082t** [comment]
@i-break-codes Thanks for your help. :facepunch:
