### ISSUE TITLE
Consider renaming project to something else

### ISSUE THREAD

**Issue by andrejsm** [i-break-codes/logerr#4]
`ejs` abbr is already taken and well known in JS community.
https://github.com/mde/ejs

**Comment by xavortm** [comment]
Some suggestions from me:
- err.js
- log.js
- jsdebug (there is npm package, but it doesn't seem active)

Not the best names ever, but its some suggestion :) If anyone has ideas let them come!

**Comment by i-break-codes** [comment]
Thanks for you suggestions, I might change once I am done adding some extra functionality and than I can decide one for the lib...

**Comment by i-break-codes** [comment]
I would love to rename this project to something like loggr.js, but I am not sure how this will impact the projects traffic, where lot of users have already shared the links to others. Still, will see once I figure out.

**Comment by jswhisperer** [comment]
I won't ever look at the library or recommend it to anyone in the js community until it doesn't steal a name from [ejs](http://www.embeddedjs.com/). It's the default of most Node projects as a templating language.

**Comment by i-break-codes** [comment]
Project is now renamed to **logerr**.
