### ISSUE TITLE
Remove the listener

### ISSUE THREAD

**Issue by shalomdotnet** [i-break-codes/logerr#7]
Right now, you're not remove the event listener before re-initialize.
So, if i wrote:

``` javascript
Error.init();
Error.init({ detailedErrors: false });
```

It's still write to console all the details.

Even worse, in case i want to remote-logging only piece of code, i write:

``` javascript
Error.init(
{
  remoteLogging: true,
  remoteSettings: {...}
});
// some code
Error.init({ remoteLogging: false });
```

If an error throw after this, two things happen:
- POST request sent to remote logger,
- It's logged in the console TWICE

**Comment by i-break-codes** [comment]
Can you send a PR which will be helpful for me to understand what you are trying to explain me here? It will surely attach an event but won't output any logs as I check the the config before throwing errors, but I would really appreciate if you have a better solution.

Thanks.

**Comment by shalomdotnet** [comment]
There were two problems in the orginal code:
1. When calling `init()` again, a new listener created, but the old is still active.
2. the old listener check his instance of config, so even if i change the config in the second call, it still check the first config.
